name: resident_zombies
description: Codeminer42 - Test

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: 4.0.4
  rxdart: 0.22.2
  google_maps_flutter: 0.5.30
  shared_preferences: 0.5.7+3

  dio: 3.0.10
  cupertino_icons: ^0.1.3
  json_serializable: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/zombie_001.png
    - assets/zombie_002.png
